name: Release

on:
  push:
    tags:
      - '*'

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GO_VERSION: 1.24
  UV_PUBLISH_TOKEN: ${{ secrets.UV_PUBLISH_TOKEN }}

permissions:
  contents: write
  id-token: write  # Required for npmjs OIDC
  discussions: write

jobs:
  release:
    name: Release
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build
        run: make build-all-platforms
      - name: Compress binaries
        run: make compress-binaries
      - name: Upload artifacts
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          make_latest: true
          files: |
            LICENSE
            ai-cli-*
  npm:
    name: Release NPM
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      # Ensure npm 11.5.1 or later is installed (required for https://docs.npmjs.com/trusted-publishers)
      - name: Update npm
        run: npm install -g npm@latest
      - name: Publish npm
        run:
          make npm-publish
  python:
    name: Release Python
    # Python logic requires the tag/release version to be available from GitHub
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v5
      - name: Publish Python
        run:
          make python-publish
